export default {
    Header: require('../assets/Images/Header.png'),
    Cart: require('../assets/Images/Cart.png'),
    Profile: require('../assets/Images/Profile.png'),
    Home: require('../assets/Images/Home.png'),
    Search: require('../assets/Images/Search.png'),
    ShoppingCart: require('../assets/Images/ShoppingCart.png'),
    RightArrow: require('../assets/Images/RightArrow.png'),
    Location: require('../assets/Images/Location.png'),
    HelpSupport: require('../assets/Images/HelpSupport.png'),
    Settings: require('../assets/Images/Settings.png'),
    Order: require('../assets/Images/Order.png'),
    Backpack: require('../assets/Images/Backpack.jpg'),
    Sunglasses: require('../assets/Images/Sunglasses.jpg'),
    Shoes: require('../assets/Images/Shoes.jpg'),
    Mug: require('../assets/Images/Mug.webp'),
    Phones: require('../assets/Images/Phones.webp'),
    Headphones: require('../assets/Images/Headphones.jpg'),
    Mouse: require('../assets/Images/Mouse.jpg'),
    Keyboard: require('../assets/Images/Keyboard.jpg'),
    Watch: require('../assets/Images/Watch.png'),
    Wallet: require('../assets/Images/Wallet.png'),
};
